-- AlterEnum
BEGIN;
DELETE FROM "Locks" WHERE "id" = 'PAYMENTS_SCRIPT';
CREATE TYPE "LockId_new" AS ENUM ('PAYMENTS_SCRIPT_ETHEREUM', 'PAYMENTS_SCRIPT_GOERLI', 'PAYMENTS_SCRIPT_BSC', 'PAYMENTS_SCRIPT_BSCT');
ALTER TABLE "Locks" ALTER COLUMN "id" TYPE "LockId_new" USING ("id"::text::"LockId_new");
ALTER TYPE "LockId" RENAME TO "LockId_old";
ALTER TYPE "LockId_new" RENAME TO "LockId";
DROP TYPE "LockId_old";
COMMIT;
