name: CD
on:
  push:
    branches:
      - master

env:
  REGISTRY: ghcr.io

jobs:
  build:
    name: Build, test, and publish
    runs-on: ubuntu-latest
    env:
      IMAGE_NAME: ${{ github.repository }}

    steps:
      - uses: actions/checkout@v2

      - uses: docker/login-action@v1
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - uses: docker/metadata-action@v3
        id: meta
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
          tags: |
            type=ref,event=branch
            type=sha

      - uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}

      - id: sha_tag
        run: echo "::set-output name=value::$(cut -d$'\n' -f2 <<<$TAGS)"
        env:
          TAGS: ${{ steps.meta.outputs.tags }}

      - uses: actions-hub/kubectl@master
        with:
          args:
            set image --namespace=swingby deployment/swingby-token-bridge app=${{
            steps.sha_tag.outputs.value }}
        env:
          KUBE_CONFIG: ${{ secrets.KUBE_CONFIG_FRONTEND }}

  bot:
    name: Build and publish bot
    runs-on: ubuntu-latest
    env:
      IMAGE_NAME: ${{ github.repository }}-bot

    steps:
      - uses: actions/checkout@v2
      - name: Put auth token into .npmrc
        run: echo "//npm.pkg.github.com/:_authToken=${GH_TOKEN}" >> .npmrc
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN_PACKAGES }}

      - uses: docker/login-action@v1
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - uses: docker/metadata-action@v3
        id: meta
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
          tags: |
            type=ref,event=branch
            type=sha

      - uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          file: ./process-bot.Dockerfile
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}

      - id: sha_tag
        run: echo "::set-output name=value::$(cut -d$'\n' -f2 <<<$TAGS)"
        env:
          TAGS: ${{ steps.meta.outputs.tags }}

      - uses: actions-hub/kubectl@master
        with:
          args:
            set image --namespace=swingby deployment/swingby-token-bridge-bot app=${{
            steps.sha_tag.outputs.value }}
        env:
          KUBE_CONFIG: ${{ secrets.KUBE_CONFIG_FRONTEND }}
