name: CD
on:
  push:
    branches:
      - master

jobs:
  build:
    name: Build, test, and publish
    runs-on: ubuntu-latest

    steps:
      - uses: docker/setup-qemu-action@v1

      - uses: crazy-max/ghaction-docker-meta@v2
        id: meta
        with:
          images: |
            rg.fr-par.scw.cloud/swingby-production/swingby-token-bridge
          tags: |
            type=ref,event=branch
            type=sha

      - id: sha_tag
        run: echo "::set-output name=value::$(cut -d$'\n' -f2 <<<$TAGS)"
        env:
          TAGS: ${{ steps.meta.outputs.tags }}

      - uses: docker/setup-buildx-action@v1

      - uses: docker/login-action@v1
        with:
          registry: rg.fr-par.scw.cloud/swingby-production
          username: nologin
          password: ${{ secrets.DOCKER_REGISTRY_PASSWORD }}

      - uses: docker/build-push-action@v2
        id: docker_build
        with:
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
