name: CI
on: [pull_request]

jobs:
  build:
    name: Build, lint, and test
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 14.x
      - name: Put auth token into .npmrc
        run: echo "//npm.pkg.github.com/:_authToken=${GH_TOKEN}" >> .npmrc
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN_PACKAGES }}
      - uses: bahmutov/npm-install@v1

      - name: Lint
        run: yarn lint

      - name: Test
        run: yarn test --ci --coverage --maxWorkers=2

      # - name: UI tests
      #   run: |
      #     yarn build
      #     yarn start & yarn wait-on http://localhost:3000
      #     yarn percy exec -- cypress run -e CI=true
      #   env:
      #     PERCY_TOKEN: ${{ secrets.PERCY_TOKEN }}
      #     DISABLE_SSR: 'yes'
